language: python
python:
- '3.6'
script: true
deploy:
  provider: pypi
  user: fridex
  password:
    secure: aqrNgFM7YLWDWplSrEC4zRg1PzeEyUiRQIRTGI8Da5Obo8hxF4ld5V9/Sqk88vMU1AGBj9JjZQbSp5grPX2Nzzj0HQBGqXOxZGpWzkIY37mE9ydAMu0Vuq/JlGDSbr695r2yBYFq/v3//bzwax/Pw4bYyt3R5Jw+oovX/u3EOn8PcULWbNgwgGnVI2MegByIY80B23hKS3j9zzJbLcN4vuSzSa1LRjHAY4TNE3nbT9wlz2Z6/JAsY1xtnMdHTfpLeSpCBJ5MxNZMkZILPbhPMiIYGbULM9FfZTrAGCOrAmRJJzvDYCi4bLe9CD+4+oJjorZtZqcuA4WX7Np0wbUPhUWG22ksOrl7//m4uFPW3CytS8u6X+5DSjxW3ewlKk2MfhhUBsYJDUN8Y39ezizW1VrwN6DCVpriEcoW4gA2T+CIkZdOkIvrwJU8jsXeebWd6+OuyYphYEBmsG+DLG6opYa4B4yheafUVY4+opqYV+EtzejGAHnV0Q8mjPxHkBNBvOGTjqpy7mmby9zWQ3a/yXe33kU/9G+vijZhb6azoFQSFkN+/SvClEmJm+7P+ArSx2C3+j54EKhxRUzb42ZxB8pK6DGZP4rwmHUA74ZkWMmXve7//dhwUGzSxICGI9UDoCBP1vxF/KaYSBVm7VNFJhQX31yvrfIVipiaVvYl6FE=
  on:
    tags: true
    branch: master
  distributions: sdist bdist_wheel
